config/routes.rb
Rails.application.routes.draw do
  resources :camps
  devise_for :users
  resources :private_data
  root to: "private_data#index"

end

app/models/birthd.rb
class Birthd < ActiveRecord::Base
	has_many :private_data
end

app/models/birthm.rb
class Birthm < ActiveRecord::Base
	has_many :private_data
end

app/models/birthy.rb
class Birthy < ActiveRecord::Base
	has_many :private_data
end

app/models/blood.rb
class Blood < ActiveRecord::Base
	has_many :private_data
end

app/models/camp.rb
class Camp < ActiveRecord::Base
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :private_data
end

app/models/private_datum.rb
class PrivateDatum < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	belongs_to :gender
	belongs_to :birthy
	belongs_to :birthm
	belongs_to :birthd
	belongs_to :blood
	belongs_to :schoolg
	belongs_to :schoolt
	belongs_to :vegetrian
	belongs_to :tshirtsize
	belongs_to :user

	validates :name, :nickname, :personcard, :address, :email, :fb, :cellphone, :urgentn, :urgentr, :urgentc, :picture, presence: true
	validates :cellphone, :urgentc, length: {is: 10, message: "手機格式錯誤"}, numericality: {only_integer: true, message: "手機格式錯誤"}
	validates :personcard, length: {is: 10, message: "身分證字號格式錯誤"}, format: {with: /[a-zA-Z]+[1-2]+[0-9]{8}/, message: "身分證字號格式錯誤"}
end

app/models/schoolg.rb
class Schoolg < ActiveRecord::Base
	has_many :private_data
end

app/models/schoolt.rb
class Schoolt < ActiveRecord::Base
	has_many :private_data
end

app/models/tshirtsize.rb
class Tshirtsize < ActiveRecord::Base
	has_many :private_data
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :private_data
end

app/models/vegetrian.rb
class Vegetrian < ActiveRecord::Base
	has_many :private_data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  # GET /camps
  # GET /camps.json
  def index
    @camps = Camp.all
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:ind, :name, :cost, :day, :date, :num, :account_name, :account_ind, :address, :contact, :expect, :intro, :ps)
    end
end

app/controllers/private_data_controller.rb
class PrivateDataController < ApplicationController
  before_action :set_private_datum, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /private_data
  # GET /private_data.json
  def index
    @private_data = PrivateDatum.all
  end

  # GET /private_data/1
  # GET /private_data/1.json
  def show
  end

  # GET /private_data/new
  def new
    @private_datum = current_user.private_data.build
  end

  # GET /private_data/1/edit
  def edit
  end

  # POST /private_data
  # POST /private_data.json
  def create
    @private_datum = current_user.private_data.build(private_datum_params)

    respond_to do |format|
      if @private_datum.save
        format.html { redirect_to @private_datum, notice: '成功新增報名資料' }
        format.json { render :show, status: :created, location: @private_datum }
      else
        format.html { render :new }
        format.json { render json: @private_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /private_data/1
  # PATCH/PUT /private_data/1.json
  def update
    respond_to do |format|
      if @private_datum.update(private_datum_params)
        format.html { redirect_to @private_datum, notice: '報名資料成功更新' }
        format.json { render :show, status: :ok, location: @private_datum }
      else
        format.html { render :edit }
        format.json { render json: @private_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_data/1
  # DELETE /private_data/1.json
  def destroy
    @private_datum.destroy
    respond_to do |format|
      format.html { redirect_to private_data_url, notice: '報名資料成功刪除' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_datum
      @private_datum = PrivateDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def private_datum_params
      params.require(:private_datum).permit(:name, :nickname, :gender_id, :birthy_id, :birthm_id, :birthd_id, :personcard, :blood_id, :school, :schoolg_id, :schoolc, :schoolt_id, :address, :email, :fb, :cellphone, :urgentn, :urgentr, :urgentc, :specialeat, :specialsick, :vegetrian_id, :tshirtsize_id, :intro, :fpick, :spick, :tpick, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/helpers/private_data_helper.rb
module PrivateDataHelper
end

app/views/camps/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>營隊編號</th>
      <th>營隊名稱</th>
      <th>營隊日期</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @camps.each do |camp| %>
      <tr>
        <td><%= camp.ind %></td>
        <td><%= link_to camp.name, camp, :style=>'color:#000000' %></td>
        <td><%= camp.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/camps/show.html.erb
<table class="table table-hover">
  <col width="12%">
  <col width="50%">
<tbody>
  <tr>
    <th>營隊編號</th>
    <th><%= @camp.ind %></th>
  </tr>
  <tr>
    <th>營隊名稱</th>
    <th><%= @camp.name %></th>
  </tr>
  <tr>
    <th>營隊天數</th>
    <th><%= @camp.day %></th>
  </tr>
  <tr>
    <th>營隊日期</th>
    <th><%= @camp.date %></th>
  </tr>
  <tr>
    <th>營隊費用</th>
    <th><%= @camp.cost %></th>
  </tr>
  <tr>
    <th>營隊人數</th>
    <th><%= @camp.num %></th>
  </tr>
  <tr>
    <th>營隊帳戶</th>
    <th><%= @camp.account_name %>
        <%= @camp.account_ind %></th>
  </tr>
  <tr>
    <th>地址</th>
    <th><%= @camp.address %></th>
  </tr>
  <tr>
    <th>聯絡人</th>
    <th><%= @camp.contact %></th>
  </tr>
  <tr>
    <th>公佈日期</th>
    <th><%= @camp.expect %></th>
  </tr>
  <tr>
    <th>營隊介紹</th>
    <th><%= @camp.intro %></th>
  </tr>
  <tr>
    <th>備註</th>
    <th><%= @camp.ps %></th>
  </tr>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>2016清大暑期營隊報名系統</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="nav navbar-nav navbar-left"><%= link_to "2016清大暑期營隊報名系統", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
        	<% if user_signed_in? -%>
						<ul class="nav navbar-nav navbar-right">
							<li><%= link_to '營隊資訊', camps_url %></li>
							<li><%= link_to '新增報名', new_private_datum_path %></li>
							<li><%= link_to '設定帳號', edit_user_registration_path %></li>
							<li><%= link_to '登出系統', destroy_user_session_path, :method => :delete %></li>
						</ul>
					<% else -%>
						<ul class="nav navbar-nav pull-right">
							<li><%= link_to '營隊資訊', camps_url %></li>
							<li><%= link_to '註冊系統', new_user_registration_path %></li>
							<li><%= link_to '登入系統', new_user_session_path %></li>
						</ul>
					<% end -%>
        </nav>
      </div>
    </div>
  </header>

	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/private_data/_form.html.erb
<%= form_for(@private_datum) do |f| %>
  <% if @private_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@private_datum.errors.count, "error") %> prohibited this private_datum from being saved:</h2>

      <ul>
      <% @private_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table table-hover">
  <tbody>
  <tr>
    <th><%= f.label "姓名" %></th>
    <th><%= f.text_field(:name, size: 8) %></th>
  </tr>
  <tr>
    <th><%= f.label "綽號" %></th>
    <th><%= f.text_field(:nickname, size: 8) %></th>
  </tr>
  <tr>
    <th><%= f.label "性別" %></th>
    <th><%= f.select :gender_id, options_from_collection_for_select(Gender.all, :id, :name, @private_datum.gender_id) %></th>
  </tr>
  <tr>
    <th><%= f.label "生日" %></th>
    <th><%= f.select :birthy_id, options_from_collection_for_select(Birthy.all, :id, :name, @private_datum.birthy_id) %>

    <%= f.label "/" %>
    <%= f.select :birthm_id, options_from_collection_for_select(Birthm.all, :id, :name, @private_datum.birthm_id) %>

    <%= f.label "/" %>
    <%= f.select :birthd_id, options_from_collection_for_select(Birthd.all, :id, :name, @private_datum.birthd_id) %></th>
  </tr>
  <tr>
    <th><%= f.label "身分證字號" %></th>
    <th><%= f.text_field(:personcard, size: 10) %></th>
  </tr>
  <tr>
    <th><%= f.label "血型" %></th>
    <th><%= f.select :blood_id, options_from_collection_for_select(Blood.all, :id, :name, @private_datum.blood_id) %></th>
  </tr>
  <tr>
    <th><%= f.label "學校" %></th>
    <th><%= f.text_field(:school, size:14) %>
    <%= f.select :schoolg_id, options_from_collection_for_select(Schoolg.all, :id, :name, @private_datum.schoolg_id) %>
    <%= f.text_field(:schoolc, size: 2) %>
    <%= f.label "班" %>
    <%= f.select :schoolt_id, options_from_collection_for_select(Schoolt.all, :id, :name, @private_datum.schoolt_id) %></th>
  </tr>
  <tr>
    <th>大頭貼</th>
    <th><%= f.file_field :picture %></th>
  </tr>
  </tbody>

  <tbody>
  <tr>
    <th><%= f.label "聯絡地址" %></th>
    <th><%= f.text_field(:address, size: 26) %></th>
  </tr>
  <tr>
    <th><%= f.label "E-mail" %></th>
    <th><%= f.text_field(:email, size: 22) %></th>
  </tr>
  <tr>
    <th><%= f.label "Facebook" %></th>
    <th><%= f.text_field(:fb, size: 22) %></th>
  </tr>
  <tr>
    <th><%= f.label "聯絡手機" %></th>
    <th><%= f.text_field(:cellphone, size: 10) %></th>
  </tr>
  <tr>
    <th><%= f.label "緊急聯絡人姓名" %></th>
    <th><%= f.text_field(:urgentn, size: 8) %></th>
  </tr>
  <tr>
    <th><%= f.label "緊急聯絡人關係" %></th>
    <th><%= f.text_field(:urgentr, size: 6) %></th>
  </tr>
  <tr>
    <th><%= f.label "緊急聯絡人手機" %></th>
    <th><%= f.text_field(:urgentc, size: 10)%></th>
  </tr>
  </tbody>

  <tbody>
  <tr>
    <th><%= f.label "特殊飲食習慣" %></th>
    <th><%= f.text_area(:specialeat, size: "20*4") %></th>
  </tr>
  <tr>
    <th><%= f.label "特殊疾病" %></th>
    <th><%= f.text_area(:specialsick, size: "20*4") %></th>
  </tr>
  <tr>
    <th><%= f.label "吃素" %></th>
    <th><%= f.select :vegetrian_id, options_from_collection_for_select(Vegetrian.all, :id, :name, @private_datum.vegetrian_id) %></th>
  </tr>
  <tr>
    <th><%= f.label "T恤大小" %></th>
    <th><%= f.select :tshirtsize_id, options_from_collection_for_select(Tshirtsize.all, :id, :name, @private_datum.tshirtsize_id) %></th>
  </tr>
  <tr>
    <th><%= f.label "自我介紹" %></th>
    <th><%= f.text_area(:intro, size: "20") %></th>
  </tr>
  </tbody>

  <tbody>
    <tr>
      <th><%= f.label "第一順位" %></th>
      <th><%= f.select :fpick, options_from_collection_for_select(Camp.all, :id, :name, @private_datum.fpick) %></th>
    </tr>
    <tr>
      <th><%= f.label "第二順位" %></th>
      <th><%= f.select :spick, options_from_collection_for_select(Camp.all, :id, :name, @private_datum.spick) %></th>
    </tr>
    <tr>
      <th><%= f.label "第三順位" %></th>
      <th><%= f.select :tpick, options_from_collection_for_select(Camp.all, :id, :name, @private_datum.tpick) %></th>
    </tr>
  </tbody>
</table>

<div class="btn-group">
  <%= f.submit "儲存送出", class: "btn btn-primary" %>
  <%= link_to '上一頁', private_data_path, data: { confirm: '改動將不會儲存，你確定？' }, class: "btn btn-warning" %>
</div>
<% end %>

app/views/private_data/edit.html.erb
<% if user_signed_in? %>
<% if @private_datum.user==current_user || current_user.wtf==777 %>
	<%= render 'form' %>
<% end %>
<% end %>

app/views/private_data/index.html.erb
<% if user_signed_in? %>
<% if current_user.wtf && current_user.wtf>=1 && current_user.wtf<=24 %>
	<table class="table table-hover">
		<thead>
			<th>名稱</th>
			<th>綽號</th>
		</thead>

		<tbody>
			<p>第一順位</p>
			<% @private_data.each do |private_datum| %>
				<% if private_datum.fpick == current_user.wtf %>
					<tr>
						<th><%= link_to private_datum.name, private_datum, :style=>'color:#000000' %></th>
						<th><%= private_datum.nickname %></th>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>

	<table class="table table-hover">
		<thead>
			<th>名稱</th>
			<th>綽號</th>
		</thead>
		
		<tbody>
			<p>第二順位</p>
			<% @private_data.each do |private_datum| %>
				<% if private_datum.spick == current_user.wtf %>
					<tr>
						<th><%= link_to private_datum.name, private_datum, :style=>'color:#000000' %></th>
						<th><%= private_datum.nickname %></th>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>

	<table class="table table-hover">
		<thead>
			<th>名稱</th>
			<th>綽號</th>
		</thead>
		
		<tbody>
			<p>第三順位</p>
			<% @private_data.each do |private_datum| %>
				<% if private_datum.tpick == current_user.wtf %>
					<tr>
						<th><%= link_to private_datum.name, private_datum, :style=>'color:#000000' %></th>
						<th><%= private_datum.nickname %></th>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>

<% else %>
<% @private_data.each do |private_datum| %>
  <% if private_datum.user==current_user || current_user.wtf==777 %>
        <%= link_to image_tag(private_datum.picture_url, size: "140", class: "img-circle"), private_datum %>
  <% end %>
<% end %>
<% end %>

<% else %>
<div class="private_datum row clearfix">
  <h2>動態消息</h2>
  <h2>留言板</h2>
</div>

<% end %>

app/views/private_data/new.html.erb
<% if user_signed_in? -%>
	<%= render 'form' %>
<% end %>

app/views/private_data/show.html.erb
<% if user_signed_in? %>
<% if @private_datum.user==current_user || current_user.wtf==777 || current_user.wtf==@private_datum.fpick || current_user.wtf==@private_datum.spick || current_user.wtf==@private_datum.tpick %>
<table class="table table-hover">
  <col width="120">
  <col width="500">
<tbody>
<p>基本資料</p>
<tr>
  <th>姓名</th>
  <th><%= @private_datum.name %></th>
</tr>
<tr>
  <th>綽號</th>
  <th><%= @private_datum.nickname %></th>
</tr>
<tr>
  <th>性別</th>
  <th><%= Gender.find(@private_datum.gender_id).name %></th>
</tr>
<tr>
  <th>生日</th>
  <th><%= Birthy.find(@private_datum.birthy_id).name+"/"+Birthm.find(@private_datum.birthm_id).name+"/"+Birthd.find(@private_datum.birthd_id).name %></th>
</tr>
<tr>
  <th>身分證字號</th>
  <th><%= @private_datum.personcard %></th>
</tr>
<tr>
  <th>血型</th>
  <th><%= Blood.find(@private_datum.blood_id).name+"型" %></th>
</tr>
<tr>
  <th>學校</th>
  <th><%= @private_datum.school+" "+Schoolg.find(@private_datum.schoolg_id).name+" "+@private_datum.schoolc+"班 "+Schoolt.find(@private_datum.schoolt_id).name %></th>
</tr>
<tr>
  <th>大頭貼</th>
  <th><%= image_tag(@private_datum.picture_url, width: 300) if @private_datum.picture.present? %></th>
</tr>
</tbody>
</table>

<table class="table table-hover">
  <col width="120">
  <col width="500">
<tbody>
<p>聯絡資料</p>
<tr>
  <th>聯絡地址</th>
  <th><%= @private_datum.address %></th>
</tr>
<tr>
  <th>E-mail</th>
  <th><%= @private_datum.email %></th>
</tr>
<tr>
  <th>Facebook</th>
  <th><%= @private_datum.fb %></th>
</tr>
<tr>
  <th>聯絡手機</th>
  <th><%= @private_datum.cellphone %></th>
</tr>
</tbody>
</table>

<table class="table table-hover">
  <col width="120">
  <col width="500">
<tbody>
<p>緊急聯絡人</p>
<tr>
  <th>緊急聯絡人姓名</th>
  <th><%= @private_datum.urgentn %></th>
</tr>
<tr>
  <th>緊急聯絡人關係</th>
  <th><%= @private_datum.urgentr %></th>
</tr>
<tr>
  <th>緊急聯絡人手機</th>
  <th><%= @private_datum.urgentc %></th>
</tr>
</tbody>
</table>

<table class="table table-hover">
  <col width="12%">
  <col width="50%">
<tbody>
<p>自我介紹</p>
<tr>
  <th>特殊飲食習慣</th>
  <th><%= @private_datum.specialeat %></th>
</tr>
<tr>
  <th>特殊疾病</th>
  <th><%= @private_datum.specialsick %></th>
</tr>
<tr>
  <th>吃素</th>
  <th><%= Vegetrian.find(@private_datum.vegetrian_id).name %></th>
</tr>
<tr>
  <th>T恤大小</th>
  <th><%= Tshirtsize.find(@private_datum.tshirtsize_id).name %></th>
</tr>
<tr>
  <th>自我介紹</th>
  <th><%= @private_datum.intro %></th>
</tr>
</tbody>
</table>

<table class="table table-hover">
  <col width="12%">
  <col width="50%">
<tbody>
<p>選秀順位</p>
<tr>
  <th>第一順位</th>
  <th><%= Camp.find(@private_datum.fpick).name %></th>
</tr>
<tr>
  <th>第二順位</th>
  <th><%= Camp.find(@private_datum.spick).name %></th>
</tr>
<tr>
  <th>第三順位</th>
  <th><%= Camp.find(@private_datum.tpick).name %></th>
</tr>
</tbody>
</table>

<div class="btn-group">
  <%= link_to '上一頁', private_data_path, class: "btn btn-primary" %>
  <%= link_to '編輯', edit_private_datum_path(@private_datum), class: "btn btn-primary" %>
  <% if @private_datum.user==current_user %>
  <%= link_to '刪除', @private_datum, method: :delete, data: { confirm: '刪除將無法復原，你確定？' }, class: "btn btn-danger" %>
  <% end %>
</div>
<% end %>
<% end %>